enum keywordTypes {
  MMORPG = 'mmorpg',
  RPG = 'rpg',
  SOUNDTRACK = 'soundtrack',
  ARCADE = 'arcade',
  EIGHTEENS = '80s',
  ADVENTURE = 'adventure',
  SHOOTER = 'shooter',
  WAR = 'wargames',
  RETRO = 'retrogames',
  ACTION = 'actiongame',
  BATTLE = 'battle',
  SURVIVAL = 'survival',
  ZOMBIE = 'zombieapocalypse',
  CRAFT = 'craft',
  FPS = 'fps',
  CARD = 'cardgame',
  VR = 'virtualreality',
  SPACESHIP = 'spaceship'
}

export const Keywords = {
  MMORPG: keywordTypes.RPG,
  RPG: keywordTypes.RPG,
  card: keywordTypes.RPG,
  dungeon: keywordTypes.RPG,
  dungeons: keywordTypes.RPG,
  'turn-based': keywordTypes.RPG,
  'character classes': keywordTypes.RPG,
  soundtrack: keywordTypes.SOUNDTRACK,
  platform: keywordTypes.ARCADE,
  '80s': keywordTypes.EIGHTEENS,
  adventure: keywordTypes.ADVENTURE,
  shooter: keywordTypes.SHOOTER,
  war: keywordTypes.WAR,
  battle: keywordTypes.WAR,
  'battle game': keywordTypes.BATTLE,
  retro: keywordTypes.RETRO,
  action: keywordTypes.ACTION,
  explosive: keywordTypes.ACTION,
  'zombie apocalypse': keywordTypes.SURVIVAL,
  zombie: keywordTypes.ZOMBIE,
  craft: keywordTypes.CRAFT,
  terrorism: keywordTypes.WAR,
  strike: keywordTypes.FPS,
  strikes: keywordTypes.FPS,
  'card-based': keywordTypes.CARD,
  deck: keywordTypes.CARD,
  'games VR': keywordTypes.VR,
  'game VR': keywordTypes.VR,
  VR: keywordTypes.VR,
  survival: keywordTypes.SURVIVAL,
  spaceship: keywordTypes.SPACESHIP,
  'tactical games': keywordTypes.RPG,
  'tactical game': keywordTypes.RPG
}
